### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by LefiloMandering** [RubberDuckShobe/audiosurf-rpc#3]
When doing an install of the RPC, doing it in the engine folder does not work.
I also tried installing the RPC in the channels folder. It brings up the Command Prompt, but then immediately shuts down.

Is there an issue with what I'm doing or is it the RPC?

**Comment by RubberDuckShobe** [comment]
This is a known issue, I'll look for another entry point soon. Sorry for the inconvenience!

**Comment by dizzydoo** [comment]
Sorry if this bumps a super-old issue, but I just wanted to throw in my two cents while giving this project another try.
I clean wiped the game folder and verified integrity using Steam to completely redownload all the files. Extracting the files and placing them in the intended folder (engine, with the channels folder and its corresponding file also copied) flashes a command prompt window for a split second, then gives me the following error messages, in this order:
![image](https://user-images.githubusercontent.com/17954168/150888130-7f160111-54fb-4439-8999-1fa06daa97cf.png)
![image](https://user-images.githubusercontent.com/17954168/150888142-b941f618-739e-416f-b555-ab53845654fd.png)

After placing all files in the release in the zip file _EXCEPT the channels folder and its Crypt.dll file_ inside the existing channels folder, the command prompt flashes before opening, saying **"DLL Attached!"** as the game window opens and loads up. The first four lines are written to the window as the game starts up and loads the files along with the integrated browser showing the audiosurf website, which causes the fifth line to be written. Even after clicking through the prompt, clicking play and choosing a mode and a song, the Discord Rich Presence under a person's profile says they're playing Audiosurf but will leave the second line as **"Loading"**. I can provide video capture if needed to demonstrate how it all happens.
![2022-01-24_20-50-58](https://user-images.githubusercontent.com/17954168/150893192-ac215242-3f64-4473-a00c-dfca23db45b2.png)

I don't fully understand how it's hooked into the game or what occurs once that output is printed, but my assumption from having this only work for me once ever and with a quick glance at the code is that the program fails when trying to find the Audiosurf window and hook itself. I say this because when the game is launched, the window starts with the name "QuestViewer" and changes it quickly to say "Audiosurf". The name change isn't reflected in Task Manager or Resource Monitor when looking at it, and continues to use "QuestViewer.exe" while appending (32-bit) for task manager in particular.

**Comment by RubberDuckShobe** [comment]
Thank you for the detailed information. Seems like it can't get the window
handle to send messages to because the DLL somehow attaches right when the
game starts (On my end, it attaches while the game is on the loading
screen, where the game loads all the DLLs from the channels folder).
I'll try coming up with a fix for that soon.

**Comment by RubberDuckShobe** [comment]
I've done a clean reinstall of Audiosurf and can reproduce this issue if I put the files in the `engine` folder.
I fixed it by making the DLL wait 500ms and try again if it can't get the window handle and published the new version on the [releases page](https://github.com/AudiosurfResearch/audiosurf-rpc/releases).

**Comment by dizzydoo** [comment]
Thanks for the update and fix! Glad I could help you narrow down the issue.
Downloaded the updated release and wanted to let you know that the error I stated previously when all files are placed in the `engine` folder still occurs, but when I place all files in the `channels` folder it works as intended and updates the rich presence perfectly.
![image](https://user-images.githubusercontent.com/17954168/151049903-4a2923f5-004e-48fc-a050-20a357faab38.png)

~~Edit: Unsure if related to the hook but sfx are broken for me, will clean install again and test to see if it's caused by it, but a minor issue.~~
Edit 2: My bad, it changed the default sfx for songs to `No Sounds`. Can ignore that.
